### ISSUE TITLE
Doesent work

### ISSUE THREAD

**Issue by NICKNMPLOL** [Tenrys/discord-emoji-stealer#1]
when running npm i 

discord-emoji-stealer-master>node index.js
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\discord-emoji-stealer-master\index.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

when running node

discord-emoji-stealer-master>node index.js
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\discord-emoji-stealer-master\index.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

**Comment by Tenrys** [comment]
You didn't run npm install properly.

**Comment by NICKNMPLOL** [comment]
how so? i wrote npm i in a cmd i launched (as admin)

**Comment by Tenrys** [comment]
You cloned the entire repository, right?

![](https://tenrys.pw/ShareX/2018/Oct/blkI.png)

**Comment by NICKNMPLOL** [comment]
yes

**Comment by Tenrys** [comment]
Works for me though, are you on linux..?

What version of npm / node are you using?
