### ISSUE TITLE
Not finding localstorage file

### ISSUE THREAD

**Issue by Golumpa** [Tenrys/discord-emoji-stealer#4]
Hey, just downloaded and tried running but can't seem to get this working correctly.

I have tried running this as administrator aswell.

Node Version: 8.12.0
NPM Version: 6.4.1
OS: Windows 10 x64

Error:
```$ node index.js
Looking for Discord process...
Found discord!
Copying application's Local Storage to temporary file...
appData: C:\Users\REMOVED\AppData\Roaming, name: discord
(node:17960) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\REMOVED\AppData\Roaming\discord\Local Storage\chrome-devtools_devtools_0.localstorage\chrome-devtools_devtools_0.localstorage-journal'
    at Object.fs.statSync (fs.js:948:11)
    at files.forEach.file (C:\Users\REMOVED\discord-emoji-stealer-master\get_token.js:45:16)
    at Array.forEach (<anonymous>)
    at getToken (C:\Users\REMOVED\discord-emoji-stealer-master\get_token.js:44:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:17960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Tenrys** [comment]
Are you using canary or ptb?

**Comment by Golumpa** [comment]
No, I am currently using the stable build

```[BUILD INFO] Release Channel: stable, Build Number: 30756```

**Comment by darrenfuller** [comment]
I am seeing a similar issue.   when i try to run on Linux, i get this error: 

`
Looking for Discord process...
Found discord!
Copying application's Local Storage to temporary file...
appData: /var/local, name: discord
(node:31465) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/home/dfuller/.config/discord/Local Storage/https_discordapp.com_0.localstorage' -> './localstorage.tmp'
    at Object.fs.copyFileSync (fs.js:1918:11)
    at getToken (/work/git/discord-emoji-stealer/get_token.js:43:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:31465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31465) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

When i create /usr/local/discord,   i then get this error:

`
Looking for Discord process...
Found discord!
Copying application's Local Storage to temporary file...
appData: /var/local, name: discord
Could not find local storage!
`

This worked previously without issues... so it's a new problem IMO

**Comment by devrism** [comment]
Can confirm, am having a similar error as darrenfuller: 
Node Version: 10.15.3
NPM Version: 6.4.1
OS: Windows 10 x64
Using the stable build

```
Looking for Discord process...
Found discord!
Copying application's Local Storage to temporary file...
appData: C:\Users\REMOVED\AppData\Roaming, name: discord
Could not find local storage!
```
